services:
  warranty-claim-service:
    build: ./backend/warranty-claim-service
    container_name: warranty-claim-service
    ports:
      - "8082:8082"
    environment:
      - DB_URL=mysql+pymysql://root:long1234@warranty-mysql:3306/warranty_claim_service
      - JWT_SECRET=super-secret-key
    depends_on:
      - warranty-mysql

  warranty-upload-service:
    build: ./backend/warranty-upload-service
    container_name: warranty-upload-service
    ports:
      - "8083:8083"
    environment:
      - DB_URL=mysql+pymysql://root:long1234@warranty-mysql:3306/warranty_claim_service
      - CLAIM_SERVICE_URL=http://warranty-claim-service:8082/claims
      - JWT_SECRET=super-secret-key
    depends_on:
      - warranty-mysql
      - warranty-claim-service

  warranty-mysql:
    image: mysql:8.0
    container_name: warranty-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: long1234
      MYSQL_DATABASE: warranty_claim_service
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth_service:
    build:
      context: ./backend
      dockerfile: auth_service/Dockerfile
    volumes:
      - ./backend/shared:/app/shared
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=mysql+pymysql://root:long1234@warranty-mysql:3306/ev_warranty_db
      - JWT_SECRET=super-secret-key
      - USER_SERVICE_URL=http://user_service:8002
    depends_on:
      warranty-mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 10s
      timeout: 5s
      retries: 10

  user_service:
    build:
      context: ./backend
      dockerfile: user_service/Dockerfile
    volumes:
      - ./backend/shared:/app/shared
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=mysql+pymysql://root:long1234@warranty-mysql:3306/ev_warranty_db
      - JWT_SECRET=super-secret-key
    depends_on:
      warranty-mysql:
        condition: service_healthy

  gateway:
    build:
      context: ./backend
      dockerfile: gateway/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/shared:/app/shared
    environment:
      - AUTH_SERVICE_URL=http://auth_service:8001
      - USER_SERVICE_URL=http://user_service:8002
      - UPLOAD_SERVICE_URL=http://warranty-upload-service:8083
      - CLAIM_SERVICE_URL=http://warranty-claim-service:8082
      - JWT_SECRET=super-secret-key
    depends_on:
      auth_service:
        condition: service_healthy
        restart: true
      user_service:
        condition: service_started
      warranty-upload-service:
        condition: service_started
      warranty-claim-service:
        condition: service_started
    restart: always
    
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm ci || npm install && npm run dev -- --host 0.0.0.0 --port 5174"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "5174:5174"
    depends_on:
      gateway:
        condition: service_started

volumes:
  mysql_data:

#networks:
  #app_net:
    #driver: bridge
