version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: long12345
      MYSQL_DATABASE: ev_warranty_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  auth_service:
    build: ./auth_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=mysql+pymysql://root:long12345@mysql:3306/ev_warranty_db
      - JWT_SECRET=super-secret-key
      - USER_SERVICE_URL=http://user_service:8002
    depends_on:
      - mysql

  user_service:
    build: ./user_service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=mysql+pymysql://root:long12345@mysql:3306/ev_warranty_db
    depends_on:
      - mysql

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    environment:
      - AUTH_SERVICE_URL=http://auth_service:8001
      - USER_SERVICE_URL=http://user_service:8002
      - JWT_SECRET=super-secret-key
    depends_on:
      - auth_service
      - user_service

volumes:
  mysql_data:
