version: "3.9"
services:
  warranty-claim-service:
    build: ./backend/warranty-claim-service
    container_name: warranty-claim-service
    ports:
      - "8082:8082"
    environment:
      - DB_URL=postgresql://postgres:password@db:5432/warranty_db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: warranty-db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: warranty_db
    ports:
      - "5433:5432"
