version: "3.9"

services:
  warranty-claim-service:
    build: ./backend/warranty-claim-service
    container_name: warranty-claim-service
    ports:
      - "8082:8082"
    environment:
      - DB_URL=mysql+pymysql://root:long1234@warranty-mysql:3306/warranty_claim_service
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: warranty-mysql
    environment:
      MYSQL_ROOT_PASSWORD: long1234
      MYSQL_DATABASE: warranty_claim_service
    ports:
      - "3307:3306"   # host:container

